# Generated by Django 4.1.2 on 2023-02-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
                ('email', models.CharField(max_length=111)),
                ('phoneno', models.CharField(max_length=111)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
